/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    /**
     * Login and retrieve an authentication token
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              authToken?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
          "multipart/form-data": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
    };
  };
  "/auth/me": {
    /**
     * Get the record belonging to the authentication token
     * <br /><br />
     * <b>Authentication:</b> required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              /** Format: email */
              email?: string | null;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
  };
  "/auth/signup": {
    /**
     * Signup and retrieve an authentication token
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              authToken?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            /** Format: email */
            email?: string;
            /** Format: password */
            password?: string;
          };
          "multipart/form-data": {
            name?: string;
            /** Format: email */
            email?: string;
            /** Format: password */
            password?: string;
          };
        };
      };
    };
  };
  [key: `/colorcategories/${number}`]: {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {
        path: {
          colorcategories_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              description?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    delete: {
      parameters: {
        path: {
          colorcategories_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    patch: {
      parameters: {
        path: {
          colorcategories_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              description?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            description?: string;
          };
          "multipart/form-data": {
            name: string;
            description?: string;
          };
        };
      };
    };
  };
  "/colorcategories": {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              description?: string;
            }[];
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              description?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            description?: string;
          };
          "multipart/form-data": {
            name: string;
            description?: string;
          };
        };
      };
    };
  };
  "/csvupload": {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            csvpaintfile?: string | null;
          };
        };
      };
    };
  };
  [key: `/manufacturers/${number}`]: {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {
        path: {
          manufacturers_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              website?: string;
              country?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    delete: {
      parameters: {
        path: {
          manufacturers_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    patch: {
      parameters: {
        path: {
          manufacturers_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              website?: string;
              country?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            website?: string;
            country?: string;
          };
          "multipart/form-data": {
            name: string;
            website?: string;
            country?: string;
          };
        };
      };
    };
  };
  "/manufacturers": {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              website?: string;
              country?: string;
            }[];
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              website?: string;
              country?: string;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            website?: string;
            country?: string;
          };
          "multipart/form-data": {
            name: string;
            website?: string;
            country?: string;
          };
        };
      };
    };
  };
  [key: `/paintlines/${number}`]: {
    /**
     * Get paintlines record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {
        path: {
          paintlines_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              /** Format: int64 */
              manufacturers_id?: number;
              description?: string;
              /** Format: int64 */
              paintlines_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Delete paintlines record.
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    delete: {
      parameters: {
        path: {
          paintlines_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Edit paintlines record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    patch: {
      parameters: {
        path: {
          paintlines_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              /** Format: int64 */
              manufacturers_id?: number;
              description?: string;
              /** Format: int64 */
              paintlines_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: int64 */
            manufacturers_id?: number;
            description?: string;
          };
          "multipart/form-data": {
            name: string;
            /** Format: int64 */
            manufacturers_id?: number;
            description?: string;
          };
        };
      };
    };
  };
  "/paintlines": {
    /**
     * Query all paintlines records
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              /** Format: int64 */
              manufacturers_id?: number;
              description?: string;
              /** Format: int64 */
              paintlines_id?: number;
            }[];
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Add paintlines record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              /** Format: int64 */
              manufacturers_id?: number;
              description?: string;
              /** Format: int64 */
              paintlines_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: int64 */
            manufacturers_id?: number;
            description?: string;
            /** Format: int64 */
            paintlines_id?: number;
          };
          "multipart/form-data": {
            name: string;
            /** Format: int64 */
            manufacturers_id?: number;
            description?: string;
            /** Format: int64 */
            paintlines_id?: number;
          };
        };
      };
    };
  };
  [key: `/paints/${number}`]: {
    /**
     * Get paints record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {
        path: {
          paints_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              color_code?: string;
              /** @enum {string} */
              medium?: "acrylic" | "oil" | "water color" | "gouache";
              /** @enum {string} */
              finish?: "matte" | "satin" | "gloss";
              /** Format: int64 */
              volume?: number;
              reference_code?: string;
              /** Format: int64 */
              paintlines_id?: number;
              color_catagories?: number[];
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Delete paints record.
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    delete: {
      parameters: {
        path: {
          paints_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Edit paints record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    patch: {
      parameters: {
        path: {
          paints_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              color_code?: string;
              /** @enum {string} */
              medium?: "acrylic" | "oil" | "water color" | "gouache";
              /** @enum {string} */
              finish?: "matte" | "satin" | "gloss";
              /** Format: int64 */
              volume?: number;
              reference_code?: string;
              /** Format: int64 */
              paintlines_id?: number;
              color_catagories?: number[];
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            color_code?: string;
            /** @enum {string} */
            medium?: "acrylic" | "oil" | "water color" | "gouache";
            /** @enum {string} */
            finish?: "matte" | "satin" | "gloss";
            /** Format: int64 */
            volume?: number;
            reference_code?: string;
            /** Format: int64 */
            paintlines_id?: number;
            color_catagories?: number[];
          };
          "multipart/form-data": {
            name: string;
            color_code?: string;
            /** @enum {string} */
            medium?: "acrylic" | "oil" | "water color" | "gouache";
            /** @enum {string} */
            finish?: "matte" | "satin" | "gloss";
            /** Format: int64 */
            volume?: number;
            reference_code?: string;
            /** Format: int64 */
            paintlines_id?: number;
            color_catagories?: number[];
          };
        };
      };
    };
  };
  "/paints": {
    /**
     * Query all paints records
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              color_code?: string;
              /** @enum {string} */
              medium?: "acrylic" | "oil" | "water color" | "gouache";
              /** @enum {string} */
              finish?: "matte" | "satin" | "gloss";
              /** Format: int64 */
              volume?: number;
              reference_code?: string;
              /** Format: int64 */
              paintlines_id?: number;
              color_catagories?: number[];
            }[];
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * Add paints record
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              name?: string;
              color_code?: string;
              /** @enum {string} */
              medium?: "acrylic" | "oil" | "water color" | "gouache";
              /** @enum {string} */
              finish?: "matte" | "satin" | "gloss";
              /** Format: int64 */
              volume?: number;
              reference_code?: string;
              /** Format: int64 */
              paintlines_id?: number;
              color_catagories?: number[];
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            color_code?: string;
            /** @enum {string} */
            medium?: "acrylic" | "oil" | "water color" | "gouache";
            /** @enum {string} */
            finish?: "matte" | "satin" | "gloss";
            /** Format: int64 */
            volume?: number;
            reference_code?: string;
            /** Format: int64 */
            paintlines_id?: number;
            color_catagories?: number[];
          };
          "multipart/form-data": {
            name: string;
            color_code?: string;
            /** @enum {string} */
            medium?: "acrylic" | "oil" | "water color" | "gouache";
            /** @enum {string} */
            finish?: "matte" | "satin" | "gloss";
            /** Format: int64 */
            volume?: number;
            reference_code?: string;
            /** Format: int64 */
            paintlines_id?: number;
            color_catagories?: number[];
          };
        };
      };
    };
  };
  [key: `/usercollections/paint/${number}`]: {
    /**
     * <br /><br />
     * <b>Authentication:</b> required
     */
    delete: {
      parameters: {
        path: {
          paints_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
  };
  [key: `/usercollections/${number}`]: {
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    get: {
      parameters: {
        path: {
          usercollections_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              /** Format: int64 */
              user_id?: number;
              /** Format: int64 */
              paints_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    delete: {
      parameters: {
        path: {
          usercollections_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": { [key: string]: unknown };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> not required
     */
    patch: {
      parameters: {
        path: {
          usercollections_id: number;
        };
      };
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              /** Format: int64 */
              user_id?: number;
              /** Format: int64 */
              paints_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            user_id?: number;
            /** Format: int64 */
            paints_id?: number;
          };
          "multipart/form-data": {
            /** Format: int64 */
            user_id?: number;
            /** Format: int64 */
            paints_id?: number;
          };
        };
      };
    };
  };
  "/usercollections": {
    /**
     * <br /><br />
     * <b>Authentication:</b> required
     */
    get: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              /** Format: int64 */
              user_id?: number;
              /** Format: int64 */
              paints_id?: number;
            }[];
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
    };
    /**
     * <br /><br />
     * <b>Authentication:</b> required
     */
    post: {
      parameters: {};
      responses: {
        /** Success! */
        200: {
          content: {
            "application/json": {
              /** Format: int64 */
              id?: number;
              /**
               * Format: timestamptz
               * @default now
               */
              created_at: number;
              /** Format: int64 */
              user_id?: number;
              /** Format: int64 */
              paints_id?: number;
            };
          };
        };
        /** Input Error. Check the request payload for issues. */
        400: unknown;
        /** Unauthorized */
        401: unknown;
        /** Access denied. Additional privileges are needed access the requested resource. */
        403: unknown;
        /** Not Found. The requested resource does not exist. */
        404: unknown;
        /** Rate Limited. Too many requests. */
        429: unknown;
        /** Unexpected error */
        500: unknown;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: int64 */
            paints_id: number;
          };
          "multipart/form-data": {
            /** Format: int64 */
            paints_id: number;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {};
}

export interface operations {}

export interface external {}
